### ISSUE TITLE
xhDimensionChooser - history feature for mobile

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-sencha#50]
The new history feature for our dimension chooser has been very well received on the desktop - time to level up the mobile / modern toolkit version.  👍 📱 

Spec very much the same. Please review and can discuss any time whatever adjustments we think we might need or any design / usability decisions that might come up.

**Comment by lbwexler** [comment]
Tom -- Can you help get this over the finish line?  Would like to get it into the the client app.  Work should be done and ready for review.

**Comment by TomTirapani** [comment]
Took a look at this... works well, is consitent with the desktop version and diff looks good.

One (minor) thing is the border on the segmented button doesn't look quite right when the history is selected:

<img width="145" alt="screen shot 2018-06-26 at 15 38 14" src="https://user-images.githubusercontent.com/3017757/41919976-9fdba998-7957-11e8-8ec4-49371f282ddc.png">
<img width="145" alt="screen shot 2018-06-26 at 15 38 17" src="https://user-images.githubusercontent.com/3017757/41919991-a90b13be-7957-11e8-8d1e-be252e4e6985.png">


A quick look at the theme css shows that the segmented button intentionally removes left borders for all but the first button. Makes sense without a selection, but looks a bit odd when we have a selection. Will take a look to see if there's a quick way to fix.

**Comment by TomTirapani** [comment]
Fixed the border - are we good to merge?

**Comment by lbwexler** [comment]
Thanks Guys -- I'll rebuild this, and we'll build it into our client app shortly.
