### ISSUE TITLE
PrefService.pushPendingAsync should fire event after server return

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-sencha#65]
Calling `prefService.pushPendingAsync` allows a client-side method to ensure a recent preference change has been fully pushed and set back on the server - e.g. before then making another call where the preference will be read server-side and it's important that the updated value is used.

However the only event prefService fires is `prefChange` immediately upon local set. We need an event that confirms that a given pref/prefs have been set on the server.

**Comment by lbwexler** [comment]
Thank You for this.  I actually encountered this last week, and commented on it in the code, and then failed to file a ticket!  

I originally was thinking just to change pushAsync() to fire the event only after completion, but I think your solution is more elegant.    How about we name this event 'prefsPushed'?  Seems like that name would be most consistent and better than, say 'prefsCommitted' or 'prefsChangeComplete'.

On the fence about plural (e.g. 'prefsPushed') vs. singular ('prefPushed').  The former will be more efficient, in the not uncommon case where you write a couple of preferences together (say after an update screen).  The latter will be more convenient for just listening for one (and not having to do an "includes" check on the name.).  Could do both, I suppose, but perhaps thats overkill and will confuse users.....
