### ISSUE TITLE
Mobile xhDimChooser throws if historyPreference value is empty

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-sencha#78]
Mobile usage of the cube dimension chooser will fail if the provided historyPreference returns an empty array (no history) for the user.

Mobile component lacks `getValue()` and base mixin class throws @ https://github.com/exhi/hoist-sencha/blob/df2060e06c69c3055991e9310cc105d401ad0840/grails-app/assets/src/xh/all/cube/BaseDimensionChooser.js#L122

Should be a quick fix but filing to not lose it and to carefully test, look and see if this should be on the base mixin vs. instances, etc.

**Note** I added a quick override for a client app as I needed to keep moving tonight with an in-place fix vs. doing a hoist-sencha build - we should be sure to unwind.

**Comment by lbwexler** [comment]
Assigning this to Don, as Don is going to put together a new Sencha-Hoist Release.  

Don -- can you test out Tom's PR, and if it looks good merge it?
