### ISSUE TITLE
Increase width of mobile xhDimChooser

### ISSUE THREAD

**Issue by amcclain** [exhi/hoist-sencha#79]
With the new history feature, rows with three-level dimension drill-downs and reasonably long dim names are quickly truncated on the phone. Would be good to give them some more room to breathe - not essential that every option always fit, but some increase in width seems warranted.

**Comment by lbwexler** [comment]
Assigning this to Don, as Don is going to put together a new Sencha-Hoist Release.

Don -- can you test out Tom's PR, and if it looks good merge it?
