### ISSUE TITLE
Admin Config Differ fails to open on first try

### ISSUE THREAD

**Issue by lbwexler** [exhi/hoist-sencha#81]
...but if you click it again, it works.  Totally reproducible.   We have seen this for a while, and decided to live with it.

On reflection, we need to fix this.  This is a critical tool, and clients use it.  Also should be an easy fix.

**Comment by febbraiod** [comment]
This is not as straightforward as it may have seemed. This is no reproducible when running locally. It is consistently reproducible in our released client apps. Have a couple of working theories for a fix, but will need to do a couple of dev client app releases to test. Will update this ticket as I go.
